# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_grp
    test_fault_wrappers_pwd
    test_fault_wrappers_unistd
    test_fault_wrappers_utmpx
)
